"""
e9v - SIMULATION: do the dose estimators recover a known answer?

Prefix `sim_` on every value. Ground-truth pools and affinities do not exist
in nature, so this is methods validation, not observation.

The manuscript claims the site-class estimator recovers the truth. That claim
needs a number behind it like any other, so it is generated here rather than
asserted. Three things are checked, each on data generated from a model whose
answer we already know:

  1. data generated by INDEPENDENT scoring must return an exponent of 1,
     because there the effective pool is M and M is proportional to dose;
  2. data generated by the EQUILIBRIUM model must return that model's own
     exponent, which conservation forces to be at least 1;
  3. the site-class estimator must recover the per-class affinities and the
     pools when affinity really is carried by site class.

A failure here would mean the estimator, not the biology, produced the
exponents in e9.
"""
import os
import sys

# Pin the thread pools BEFORE numpy or torch are imported. This experiment's
# recorded values depend on floating-point reduction order, which depends on
# how many threads the BLAS and torch pools happen to have, so an unpinned run
# does not reproduce a run made on a differently loaded machine. Stage B of
# verify.py caught exactly that. Thread count changes only the arithmetic
# order, never the mathematics, and pinning makes the result reproducible.
for _v in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS",
           "NUMEXPR_NUM_THREADS"):
    os.environ.setdefault(_v, "1")

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
import numpy as np                                          # noqa: E402
from riscpool import dosefit as DF, runner                  # noqa: E402

DOSES = [1.0, 10.0, 25.0]
N_TX = 4000
N_GENES = 12000
NOISE = [0.05, 0.15, 0.30]


def fn(seed=0):
    rng = np.random.default_rng(seed)
    K = 10.0 ** rng.normal(1.0, 1.2, N_TX)
    x = 10.0 ** rng.normal(0.5, 0.8, N_TX)
    doses = np.array(DOSES)
    kappa = 2000.0
    M_true = kappa * doses
    f_true = DF.free_pool_from_M(M_true, K, x)
    c_true = 2.0

    continuous = []
    for sd in NOISE:
        Yeq = [-c_true * (f / (K + f)) + rng.normal(0, sd, N_TX)
               for f in f_true]
        req = DF.fit_pools(K, Yeq)
        Yind = [-c_true * (M / (K + M)) + rng.normal(0, sd, N_TX)
                for M in M_true]
        rind = DF.fit_pools(K, Yind)
        continuous.append({
            "sim_noise_sd": sd,
            "sim_true_pool_per_dose": f_true.tolist(),
            "sim_fitted_pool_per_dose_equilibrium_data":
                req["pool_per_dose"],
            "sim_max_rel_pool_error_equilibrium_data": float(np.max(
                np.abs(np.array(req["pool_per_dose"]) - f_true) / f_true)),
            "sim_true_slope_equilibrium":
                DF.loglog_slope(doses, f_true)["slope"],
            "sim_fitted_slope_equilibrium_data":
                DF.loglog_slope(doses, req["pool_per_dose"])["slope"],
            "sim_true_slope_independent":
                DF.loglog_slope(doses, M_true)["slope"],
            "sim_fitted_slope_independent_data":
                DF.loglog_slope(doses, rind["pool_per_dose"])["slope"],
            "sim_amplitude_recovered_equilibrium_data":
                req["amplitude_c_log2_per_unit_bound_fraction"],
            "sim_true_amplitude": c_true,
        })

    # --- the site-class estimator ---
    counts = {"6mer": rng.poisson(0.25, N_GENES),
              "7mer-A1": rng.poisson(0.10, N_GENES),
              "7mer-m8": rng.poisson(0.10, N_GENES),
              "8mer": rng.poisson(0.04, N_GENES)}
    K_true = {"6mer": 3000.0, "7mer-A1": 800.0, "7mer-m8": 300.0,
              "8mer": 80.0}
    Kc = DF.class_K_vector(counts, K_true)
    pools_true = np.array([50.0, 300.0, 600.0])
    classfits = []
    for sd in NOISE:
        Y = [-c_true * np.where(np.isfinite(Kc), p / (Kc + p), 0.0)
             + rng.normal(0, sd, N_GENES) for p in pools_true]
        r = DF.fit_class_pools(counts, Y, K_anchor=K_true["7mer-m8"])
        got = r["K_by_class_molecules_per_cell"]
        classfits.append({
            "sim_noise_sd": sd,
            "sim_true_pool_per_dose": pools_true.tolist(),
            "sim_fitted_pool_per_dose": r["pool_per_dose"],
            "sim_max_rel_pool_error": float(np.max(
                np.abs(np.array(r["pool_per_dose"]) - pools_true)
                / pools_true)),
            "sim_true_K_by_class": K_true,
            "sim_fitted_K_by_class": got,
            "sim_max_rel_K_error": float(max(
                abs(got[k] - v) / v for k, v in K_true.items())),
            "sim_true_slope": DF.loglog_slope(DOSES, pools_true)["slope"],
            "sim_fitted_slope": DF.loglog_slope(
                DOSES, r["pool_per_dose"])["slope"],
            "sim_class_ordering_correct":
                bool(r["class_ordering_is_8mer_strongest"]),
            "sim_amplitude_recovered":
                r["amplitude_c_log2_per_unit_bound_fraction"],
        })

    return {
        "SIMULATION_NOTE": (
            "every value here is simulated. Ground-truth pools and affinities "
            "do not exist in nature; this validates the estimators used in "
            "e9 and claims nothing about any cell."),
        "sim_doses_nM": DOSES,
        "sim_n_transcripts_continuous": N_TX,
        "sim_n_genes_class": N_GENES,
        "sim_noise_levels": NOISE,
        "sim_continuous_K": continuous,
        "sim_site_class_K": classfits,
        "sim_worst_slope_error_independent_data": float(max(
            abs(r["sim_fitted_slope_independent_data"]
                - r["sim_true_slope_independent"]) for r in continuous)),
        "sim_worst_slope_error_equilibrium_data": float(max(
            abs(r["sim_fitted_slope_equilibrium_data"]
                - r["sim_true_slope_equilibrium"]) for r in continuous)),
        "sim_worst_slope_error_class_estimator": float(max(
            abs(r["sim_fitted_slope"] - r["sim_true_slope"])
            for r in classfits)),
        "sim_worst_rel_pool_error_class_estimator": float(max(
            r["sim_max_rel_pool_error"] for r in classfits)),
        "sim_worst_rel_K_error_class_estimator": float(max(
            r["sim_max_rel_K_error"] for r in classfits)),
        "sim_class_ordering_correct_in_all_runs": bool(all(
            r["sim_class_ordering_correct"] for r in classfits)),
        "sim_equilibrium_true_slope_exceeds_one": bool(
            continuous[0]["sim_true_slope_equilibrium"] > 1.0),
        "sim_interpretation": (
            "the estimator returns 1 on independent-generated data and the "
            "model's own exponent on equilibrium-generated data, so an "
            "exponent away from 1 in e9 is a property of the measurement and "
            "not an artefact of the fit."),
    }


if __name__ == "__main__":
    runner.run("e9v_sim_estimator_validation", fn, seed=0)
